// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aozyvpinhgciheewhhxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvenl2cGluaGdjaWhlZXdoaHh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDk1MTYsImV4cCI6MjA3MjU4NTUxNn0.yjv_KtC7YI7ftWeCQRIeNH4i0AGSie-S7asaAoBWwsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});